const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const cleanCode=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
const makeCode=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join('');};
const safeState=v=>({activeQuest:String(v?.activeQuest||'').slice(0,40),memories:Array.isArray(v?.memories)?v.memories.filter(x=>['rootwell','ruins','shrine'].includes(x)):[],completed:Array.isArray(v?.completed)?v.completed.map(String).slice(0,8):[],bossDefeated:v?.bossDefeated===true});
const merge=(a,b)=>({activeQuest:b.activeQuest||a.activeQuest||'',memories:[...new Set([...(a.memories||[]),...b.memories])],completed:[...new Set([...(a.completed||[]),...b.completed])],bossDefeated:!!(a.bossDefeated||b.bossDefeated)});
export default {async fetch(request,env){const url=new URL(request.url);try{
  if(request.method==='POST'&&url.pathname==='/api/lobby'){const body=await request.json(),playerId=String(body.playerId||'').slice(0,80),name=String(body.name||'Wayfarer').slice(0,24);if(!playerId)return json({error:'Missing player id'},400);let lobbyCode=cleanCode(body.code),row=lobbyCode?await env.DB.prepare('SELECT code, state_json FROM lobbies WHERE code = ?').bind(lobbyCode).first():null;if(lobbyCode&&!row)return json({error:'Lobby not found'},404);if(!row){for(let i=0;i<6&&!row;i++){lobbyCode=makeCode();const exists=await env.DB.prepare('SELECT code FROM lobbies WHERE code = ?').bind(lobbyCode).first();if(!exists){await env.DB.prepare('INSERT INTO lobbies (code, state_json, updated_at) VALUES (?, ?, ?)').bind(lobbyCode,'{}',Date.now()).run();row={code:lobbyCode,state_json:'{}'};}}}await env.DB.prepare('INSERT INTO lobby_players (lobby_code, player_id, name, x, z, yaw, seen_at) VALUES (?, ?, ?, 0, 88, 0, ?) ON CONFLICT(lobby_code, player_id) DO UPDATE SET name=excluded.name, seen_at=excluded.seen_at').bind(lobbyCode,playerId,name,Date.now()).run();return json({code:lobbyCode,state:JSON.parse(row.state_json||'{}')});}
  const match=url.pathname.match(/^\/api\/lobby\/([A-Z0-9]{6})\/sync$/);if(request.method==='POST'&&match){const lobbyCode=match[1],body=await request.json(),playerId=String(body.playerId||'').slice(0,80),now=Date.now();if(!playerId)return json({error:'Missing player id'},400);const lobby=await env.DB.prepare('SELECT state_json FROM lobbies WHERE code = ?').bind(lobbyCode).first();if(!lobby)return json({error:'Lobby not found'},404);const state=merge(JSON.parse(lobby.state_json||'{}'),safeState(body.state));await env.DB.prepare('UPDATE lobbies SET state_json = ?, updated_at = ? WHERE code = ?').bind(JSON.stringify(state),now,lobbyCode).run();await env.DB.prepare('INSERT INTO lobby_players (lobby_code, player_id, name, x, z, yaw, seen_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(lobby_code, player_id) DO UPDATE SET name=excluded.name, x=excluded.x, z=excluded.z, yaw=excluded.yaw, seen_at=excluded.seen_at').bind(lobbyCode,playerId,String(body.name||'Wayfarer').slice(0,24),Number(body.x)||0,Number(body.z)||0,Number(body.yaw)||0,now).run();const rows=await env.DB.prepare('SELECT player_id AS id, name, x, z, yaw FROM lobby_players WHERE lobby_code = ? AND seen_at > ? ORDER BY seen_at DESC LIMIT 8').bind(lobbyCode,now-12000).all();return json({state,players:rows.results||[]});}
  // Worker asset bindings do not implicitly map `/` to the Vite entry file.
  // Preserve real asset paths, but send navigation routes to index.html.
  if(request.method==='GET'&&(url.pathname==='/'||!url.pathname.includes('.'))){const assetUrl=new URL('/index.html',url);return env.ASSETS.fetch(new Request(assetUrl,request));}
  return env.ASSETS.fetch(request);
}catch(error){console.error(error);return json({error:'Temporary server error'},500);}}};
